#!/bin/bash
#
set -e -o pipefail

SCRIPT_DIR=$( dirname -- "$( readlink -f -- "$0"; )"; )
DISTRO="ubuntu"
DISTRO_VERSION="22.04"
IMAGE_DIR="$DISTRO-$DISTRO_VERSION"

main() {
  check_required_programs
  create_release_dir
  download_latest_cloud_image
  verify_download
  copy_image_file
}

check_required_programs() {
  PROGRAM_NOT_FOUND=0

  required_program curl
  required_program virt-customize
  required_program qm
  required_program sha256sum

  if [ $PROGRAM_NOT_FOUND -ne 0 ]; then
    exit 1 
  fi 
}

required_program() {
  if ! type "$1" &>/dev/null; then
    echo "[Error] required program not found: '$1'"
    PROGRAM_NOT_FOUND=1
  fi
}

download_latest_cloud_image() {
  if [ -z "$(ls $IMAGE_DIR/$(release_tag))" ]; then
    curl --output-dir $IMAGE_DIR/$(release_tag) --remote-name-all $(all_download_files)
  fi
}

create_release_dir() {
  local release_tag=$(release_tag)
  local release_dir=$IMAGE_DIR/$release_tag
  if [ ! -d $release_dir ]; then
    mkdir -p $release_dir
    ln -s -r -f $release_dir $IMAGE_DIR/latest 
  fi
}

RELEASE_TAG=''
release_tag() {
  if [ -z $RELEASE_TAG ]; then
    RELEASE_TAG=$($SCRIPT_DIR/ubuntu-cloud-image-latest --release-tag)
  fi
  echo $RELEASE_TAG
}

all_download_files() {
  echo $($SCRIPT_DIR/ubuntu-cloud-image-latest --image --checksum --manifest)
}

verify_download() {
  pushd $IMAGE_DIR/latest/ &>/dev/null
  if ! sha256sum -c --ignore-missing SHA256SUMS &>/dev/null; then
    echo "[Error] Checksum validation failed"
    exit 1
  else
    echo "[Info] Checksum validation OK"
  fi
  popd &>/dev/null
}

copy_image_file() {
  pushd $IMAGE_DIR/latest/ &>/dev/null
  local img_file=$(ls *.img | head -n1) 
  cp --no-clobber $img_file $(basename --suffix='.img' $img_file).modified.img
  popd &>/dev/null
}

main
